export type Language = 'th' | 'en';
export type Mode = 'light' | 'dark';

export const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.home': 'Home',
        'nav.report': 'Report',
        'nav.help': 'Help',
        'nav.language': 'Language',
        'nav.light': 'Light',
        'nav.dark': 'Dark',
        'side.priceList': 'Posting Price List',
        'side.ticket': 'Ticket',
        'side.chat': 'ZY Chat',
        'page.title': 'Price Management',
        'page.createBtn': 'Create Price Card',
        'tab.timeline': 'Timeline View',
        'tab.cards': 'Card View',
        'form.createTitle': 'Create New Price Card',
        'form.editTitle': 'Edit Price Card',
        'form.subtitle': 'Fill in the details below to set the pricing for a specific period.',
        'form.resource': 'Resource Name',
        'form.price': 'Unit Price (THB)',
        'form.start': 'Start Date',
        'form.end': 'End Date',
        'form.cancel': 'Cancel',
        'form.submitUpdate': 'Update Price',
        'form.submitCreate': 'Create Price',
        'msg.created': 'Price card created successfully',
        'msg.updated': 'Price card updated successfully',
        'msg.deleted': 'Price card deleted successfully',
        'msg.duplicated': 'Price card duplicated successfully',
        'search.placeholder': 'Search by resource name...',
        'card.valid': 'Valid',
        'card.unitPrice': 'UNIT PRICE',
        'card.scheduleOverlap': 'Schedule Overlap',
        'card.daysLeft': 'days left',
        'status.all': 'All',
        'status.active': 'Active',
        'status.expired': 'Expired',
        'status.upcoming': 'Upcoming',
        'msg.overlapError': 'Overlap detected! Each wood can only have one price per day.',
        'ticket.title': 'Create Ticket',
        'ticket.btnManual': 'Manual Create',
        'ticket.btnAuto': 'Pull from Weighbridge',
        'ticket.number': 'Ticket No.',
        'ticket.type': 'Creation Mode',
        'ticket.paymentType': 'Payment Type',
        'ticket.payment.cash': 'Cash',
        'ticket.payment.po': 'PO',
        'ticket.seller': 'Seller / Company',
        'ticket.product': 'Product',
        'ticket.licensePlate': 'License Plate',
        'ticket.vehicleType': 'Vehicle Type',
        'ticket.weightIn': 'Weight In',
        'ticket.weightOut': 'Weight Out',
        'ticket.netWeight': 'Net Weight',
        'ticket.entryTime': 'Entry Date-Time',
        'ticket.exitTime': 'Exit Date-Time',
        'ticket.impurity': 'Impurity (%)',
        'ticket.moisture': 'Moisture (%)',
        'ticket.remainingWeight': 'Rem. Weight',
        'ticket.totalPrice': 'Total Amount',
        'ticket.remarks': 'Remarks',
        'ticket.recorder': 'Recorded by',
        'ticket.btnPrint': 'Print Ticket',
        'ticket.btnSave': 'Save Data',
        'ticket.status.success': 'Success',
        'ticket.status.draft': 'Draft',
        'ticket.status.pending': 'Pending',
        'ticket.status.approved': 'Approved',
        'ticket.action.approve': 'Approve',
        'ticket.msg.approved': 'Ticket approved successfully',
        'ticket.msg.saved': 'Ticket saved successfully',
    },
    th: {
        'nav.home': 'หน้าหลัก',
        // ... (cutting for brevity in replace_file_content, will provide full block)
        'nav.report': 'รายงาน',
        'nav.help': 'ช่วยเหลือ',
        'nav.language': 'ภาษา',
        'nav.light': 'โหมดสว่าง',
        'nav.dark': 'โหมดมืด',
        'side.priceList': 'รายการราคาประกาศ',
        'side.ticket': 'ตั๋วสินค้า',
        'side.chat': 'ZY แชท',
        'page.title': 'การจัดการราคา',
        'page.createBtn': 'สร้างบัตรราคา',
        'tab.timeline': 'มุมมองปฏิทิน',
        'tab.cards': 'มุมมองการ์ด',
        'form.createTitle': 'สร้างบัตรราคาใหม่',
        'form.editTitle': 'แก้ไขบัตรราคา',
        'form.subtitle': 'กรอกรายละเอียดด้านล่างเพื่อกำหนดราคาในช่วงเวลาที่ต้องการ',
        'form.resource': 'ชื่อวัตถุดิบ',
        'form.price': 'ราคาต่อหน่วย (บาท)',
        'form.start': 'วันที่เริ่มต้น',
        'form.end': 'วันที่สุด',
        'form.cancel': 'ยกเลิก',
        'form.submitUpdate': 'อัปเดตราคา',
        'form.submitCreate': 'สร้างราคา',
        'msg.created': 'สร้างบัตรราคาสำเร็จ',
        'msg.updated': 'อัปเดตบัตรราคาสำเร็จ',
        'msg.deleted': 'ลบบัตรราคาสำเร็จ',
        'msg.duplicated': 'คัดลอกบัตรราคาสำเร็จ',
        'search.placeholder': 'ค้นหาตามชื่อวัตถุดิบ...',
        'card.valid': 'มีผล',
        'card.unitPrice': 'ราคาต่อหน่วย',
        'card.scheduleOverlap': 'ช่วงเวลาซ้อนทับกัน',
        'card.daysLeft': 'วันที่เหลือ',
        'status.all': 'ทั้งหมด',
        'status.active': 'ใช้งานอยู่',
        'status.expired': 'หมดอายุ',
        'status.upcoming': 'เร็วๆ นี้',
        'msg.overlapError': 'ตรวจพบช่วงเวลาที่ทับซ้อนกัน! ไม้แต่ละชนิดสามารถมีได้เพียง 1 ราคาต่อวันเท่านั้น',
        'ticket.title': 'สร้างตั๋วสินค้า',
        'ticket.btnManual': 'สร้างด้วยตนเอง',
        'ticket.btnAuto': 'ดึงข้อมูลจากเครื่องชั่ง',
        'ticket.number': 'เลขที่ตั๋ว',
        'ticket.type': 'โหมดการสร้าง',
        'ticket.paymentType': 'ประเภทการจ่ายเงิน',
        'ticket.payment.cash': 'เงินสด (Cash)',
        'ticket.payment.po': 'เครดิต (PO)',
        'ticket.seller': 'ชื่อผู้ค้า / บริษัท',
        'ticket.product': 'สินค้า',
        'ticket.licensePlate': 'ทะเบียนรถ',
        'ticket.vehicleType': 'ประเภทรถ',
        'ticket.weightIn': 'น้ำหนักเข้า (Weight In)',
        'ticket.weightOut': 'น้ำหนักรถเปล่า (Weight Out)',
        'ticket.netWeight': 'น้ำหนักสุทธิ (NET WEIGHT)',
        'ticket.entryTime': 'วันที่-เวลา เข้า',
        'ticket.exitTime': 'วันที่-เวลา ออก',
        'ticket.impurity': 'หักสิ่งปลอมปน (%)',
        'ticket.moisture': 'หักความชื้น (%)',
        'ticket.remainingWeight': 'นน. คงเหลือ',
        'ticket.totalPrice': 'รวมเงินทั้งสิ้น',
        'ticket.remarks': 'หมายเหตุ',
        'ticket.recorder': 'ผู้บันทึกรายการ',
        'ticket.btnPrint': 'พิมพ์ใบชั่ง',
        'ticket.btnSave': 'บันทึกข้อมูล',
        'ticket.status.success': 'เสร็จสิ้น (Success)',
        'ticket.status.draft': 'แบบร่าง',
        'ticket.status.pending': 'รออนุมัติ',
        'ticket.status.approved': 'อนุมัติแล้ว',
        'ticket.action.approve': 'อนุมัติ',
        'ticket.msg.approved': 'อนุมัติตั๋วสินค้าสำเร็จ',
        'ticket.msg.saved': 'บันทึกตั๋วสินค้าสำเร็จ',
    }
};
